DROP DATABASE IF EXISTS deploy_system_db;
CREATE DATABASE IF NOT EXISTS deploy_system_db;
use deploy_system_db;

DROP TABLE IF EXISTS java_project_info;
CREATE TABLE IF NOT EXISTS java_project_info (
PROJECT_ID INT AUTO_INCREMENT,
DESCRIPTION VARCHAR(100),
URL VARCHAR(2083),
PRIMARY KEY (PROJECT_ID)
);